### ISSUE TITLE
Not working with webpack 5

### ISSUE THREAD

**Issue by Andreychikov-Vasiliy** [mikeerickson/todo-webpack-plugin#22]
TypeError: Cannot read property 'forEach' of undefined
todo-webpack-plugin/index.js:42:13

**Comment by Andreychikov-Vasiliy** [comment]
`
  apply: function(compiler) {
    compiler.hooks.done.tap('TodoWebpackPlugin', params => {
      return reporter(
        this.pluginOpts,
        params.compilation.fileDependencies
      );
    });
  }
`
looks like fixing

**Comment by mikeerickson** [comment]
Fixed 1.10 https://github.com/mikeerickson/todo-webpack-plugin/releases/tag/v1.10.0
