### ISSUE TITLE
How to ignore TODO's from node_modules?

### ISSUE THREAD

**Issue by pbojinov** [mikeerickson/todo-webpack-plugin#4]
I ran the example from "Getting Started" and it created a bunch of TODO's for all my `node_modules`. Any way to restrict this to just my codebase?

```
### TODOs
| Filename | line # | TODO
|:------|:------:|:------
| /Users/petarbojinov/project-xyz/node_modules/babel-polyfill/node_modules/core-js/modules/_typed-array.js | 287 | add validation descriptor w/o calling accessors
| /Users/petarbojinov/project-xyz/node_modules/history/lib/useQueries.js | 64 | Instead of all the book-keeping here, this should just strip the
| /Users/petarbojinov/project-xyz/node_modules/intl-messageformat/lib/core.js | 143 | Provide anything else?
| /Users/petarbojinov/project-xyz/node_modules/react-bootstrap/lib/Fade.js | 35 | Remove duplication once #977 is resolved.
```

**Comment by mikeerickson** [comment]
@pbojinov the plugin uses whatever is passed through to webpack.  Can you please share your `webpack.config.js` file so I can see your setup.

**Comment by mikeerickson** [comment]
Fixed with [v1.3.0](https://github.com/mikeerickson/todo-webpack-plugin/tree/v1.3.0)

**Comment by pbojinov** [comment]
I'm using the `react-redux-starter-kit`, so my webpack config is same as: https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js

@mikeerickson thanks for adding support for ignoring `node_modules`!

**Comment by mikeerickson** [comment]
@pbijinov does the 1.3.0 update mentioned above not cure the problem?  I am now excluding any file contained in `node_modules` automatically (ala the way ESLint excludes)

**Comment by mikeerickson** [comment]
@pbojinov please see about (referenced incorrect name)

**Comment by pbojinov** [comment]
@mikeerickson yes, the 1.3.0 and 1.4.0 updates work as described. Thank you for the quick turnaround!
