### ISSUE TITLE
Relative file name output?

### ISSUE THREAD

**Issue by FuzzOli87** [mikeerickson/todo-webpack-plugin#8]
It would be extremely helpful if we could have it print out filenames on a relative path to the project and not the full path of my local machine. 

When I get sometime this week I can look into doing a PR.

**Comment by mikeerickson** [comment]
@FuzzOli87 I will have a look at this request in next day or so.

**Comment by mikeerickson** [comment]
@FuzzOli87 Updated plugin, now supports `relativeFilePath` option (and is now default)

[Version 1.7.1](https://www.npmjs.com/package/todo-webpack-plugin) contains update
