### ISSUE TITLE
Support withInlineFiles option

### ISSUE THREAD

**Issue by bjunc** [mikeerickson/todo-webpack-plugin#9]
My use case was to use with `.vue` files that have `<template/>`, `<script/>` and `<style/>` tags.

To get this working minimally, `withInlineFiles` option can be added to `DEFAULT_OPTIONS` and passed to `leasot.parse()`:

```
// index.js
const DEFAULT_OPTIONS = {
  console:            true,       // default true
  tags:               [],         // default TODO
  reporter:           'markdown', // default markdown
  skipUnsupported:    true,       // skip unsupported files
  suppressFileOutput: false,      // don't output to file,
  relativeFilePath:   true,       // display relative file paths in report
  withInlineFiles:    false       // parse possible inline files
};

function reporter(options, files) {
    var todo = leasot.parse({
        ext:              path.extname(file),
        content:          fs.readFileSync(file, 'utf8'),
        fileName:         file,
        customTags:       options.tags,
        reporter:         options.reporter,
        withInlineFiles:  options.withInlineFiles
    });
};
```

```
// webpack.config.js
plugins: [
    new TodoWebpackPlugin({
        withInlineFiles: 	true
    })
],
```

Also, to work with`.vue`, leasot needs to be updated to 4.3.1

**Comment by mikeerickson** [comment]
@bjunc Thank you for information, I will get this addressed over the weekend (unless I gather some more time in the next couple days).   If you dont hear back from me in appropriate time, please give me a ping :-)

**Comment by tyler36** [comment]
I'm was just about to ask for a ```leasot``` version bump for ```.vue``` file support

**Comment by mikeerickson** [comment]
@tyler36 @bjunc I will be taking care of this issue over the weekend, I will let you all know when it is ready.  Thank you for your patience (real life job is keeping me beyond busy at the moment)

**Comment by tyler36** [comment]
Thanks for the update :)

**Comment by bjunc** [comment]
@mikeerickson, just added a pull request.  Not sure if you have a collaboration protocol, but I figured just getting the commits to you would be a good start.

@tyler36, this works with `.vue` files

**Comment by mikeerickson** [comment]
Added in 1.8 release
